### ISSUE TITLE
No `a` value optimisation

### ISSUE THREAD

**Issue by Yamakaky** [techcompliant/DASM#5]
In `DCPU.cpp`, I could find how you manage the fact that the `a` value can be optimized if it is small enough. Is it implemented?

**Comment by eva-knight** [comment]
Yes, "a" values get optimized here:

if(isA && -1 <= value && value <= 30 && !increment)
    {//Only argument A can use the short-form literals
                        ret_word = word(0x21 + value);
                        next_word = false;
                    }
                    else
                        ret_word = 0x1F;

Note that delayed evaluation expressions (such as referencing labels or defines that are further ahead in code) will not be optimized (because this can change the value of labels it is using, eg if label is -1 but optimizing this instruction would make it go to -2, which then would be incorrect).

**Comment by Yamakaky** [comment]
Oh yeay, sorry.
In [my code](https://github.com/Yamakaky/dcpu/blob/master/src/assembler/linker.rs), I loop until the labels are stabilized. It's fast enough for the use case. It allows labels backward and forward, and local labels.
